<!-- Modal -->
<div id="signup-modal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Registration form</h4>
            </div>
            <div class="modal-body">
                <form method="POST" id="signupForm" class="form-group" action="?controller=users&action=register">
                    <div class="form-group has-feedback">
                        <label for="username">Username:</label>
                        <input type="username" class="form-control" id="usernameSignUp" name="username" placeholder="Enter username">
                        <span class="glyphicon form-control-feedback" id="usernameSignUp1"></span>
                    </div>
                    <div class="form-group has-feedback">
                        <label for="email">Email:</label>
                        <input type="email" class="form-control" id="emailSignUp" name="email" placeholder="Enter email">
                    </div>
                    <div class="form-group has-feedback">
                        <label for="password">Password:</label>
                        <input type="password" class="form-control" id="passwordSignUp" name="password" placeholder="Enter password">
                    </div>
                    <div class="form-group has-feedback">
                        <label for="confirmpassword">Confirm Password:</label>
                        <input type="password" class="form-control" id="confirmpasswordSignUp" placeholder="Confirm password">
                    </div>
                    <td><input id="signUpButton" type="submit" class="btn btn-default" name="signUpButton" value="Sign-Up"></td>

                </form>


            </div>
            <div class="modal-footer">
                <label>So close. Just fill it up!</label>
            </div>
        </div>
    </div>
</div>


